export enum WorkerType {
  SPECIAL = 'SPECIAL',
  EXCLUDE = 'EXCLUDE',
  SHORTHALF = 'SHORTHALF',
  OVER1YEAR = 'OVER1YEAR',
  UNDER1YEAR = 'UNDER1YEAR',
}

export enum ProgressStatus {
  PENDIG = 'PENDING',
  PROCESSING = 'PROCESSING',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}

export enum ProgressDetail {
  AUTHFAILED = 'AUTHFAILED',
  SYSTEMFAILED = 'SYSTEMFAILED',
  NOCANDIDATE = 'NOCANDIDATE',
  NOREFUNDABLE = 'NOREFUNDABLE',
  REFUNDABLE = 'REFUNDABLE',
}

export enum RefundStatus {
  APPLY = 'APPLY',
  CANCEL = 'CANCEL',
  PROCESSING = 'PROCESSING',
  HOLD = 'HOLD',
  COMPLETED = 'COMPLETED',
}

export enum AuthType {
  SIMPLEAUTH = 'SIMPLEAUTH',
  GENERALAUTH = 'GENERALAUTH',
}
